#!/bin/bash

ver="0.31"
wget http://ck.kolivas.org/apps/interbench/interbench-${ver}.tar.bz2 -O interbench-${ver}.tar.bz2
tar -xf interbench-${ver}.tar.bz2
cd interbench-${ver}
make clean && make interbench && cp interbench ..
if [ $? -eq 0 ]
then
	touch ../.installed
fi
