#!/usr/bin/python3

import subprocess
import time
import sys

forks = int(sys.argv[1])

ps = []
start = time.time()
for i in range(0, forks):
	ps.append(subprocess.Popen(['./pipe-test']))

for i in ps:
	i.wait()
end = time.time()
print(end - start - 5)
