#!/bin/bash

# This file is executed for the test-run. Do not make preperations for the test
# in this file, because the monitors are running and would record false data.
# Return the results as a comma-seperated list of integers or floats. Do not
# use multiple lines for the return values.
echo "{ \"value\" :  "
date $@
echo "}"
