#!/usr/bin/python3

# Try to generate the exact same file by using the same seed

import random
import struct

random.seed(0)

end = 1024*1024*1024

f = open('testfile', 'wb')
for i in range(0, int(end/8)):
	f.write(struct.pack('Q', random.randrange(0, 2**64)))
f.close()


